/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPhotoViewModelFromDiscriminatorValue, createProblemDetailsFromDiscriminatorValue, serializePhotoViewModel, type PhotoViewModel, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { ImageRequestBuilderRequestsMetadata, type ImageRequestBuilder } from './image/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Photo/{id}
 */
export interface PhotoItemRequestBuilder extends BaseRequestBuilder<PhotoItemRequestBuilder> {
    /**
     * The image property
     */
    get image(): ImageRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PhotoViewModel>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PhotoViewModel | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ProblemDetails} error when the service returns a 400 status code
     * @throws {ProblemDetails} error when the service returns a 404 status code
     */
     put(body: PhotoViewModel, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: PhotoViewModel, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PhotoItemRequestBuilderUriTemplate = "{+baseurl}/api/Photo/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PhotoItemRequestBuilderNavigationMetadata: Record<Exclude<keyof PhotoItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    image: {
        requestsMetadata: ImageRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const PhotoItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: PhotoItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createPhotoViewModelFromDiscriminatorValue,
    },
    put: {
        uriTemplate: PhotoItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        errorMappings: {
            400: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePhotoViewModel,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
