/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PersonItemRequestBuilderRequestsMetadata, type PersonItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { RequestRequestBuilderRequestsMetadata, type RequestRequestBuilder } from './request/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Person
 */
export interface PersonRequestBuilder extends BaseRequestBuilder<PersonRequestBuilder> {
    /**
     * The request property
     */
    get request(): RequestRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.Person.item collection
     * @param id Unique identifier of the item
     * @returns {PersonItemRequestBuilder}
     */
     byId(id: Guid) : PersonItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PersonRequestBuilderUriTemplate = "{+baseurl}/api/Person";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PersonRequestBuilderNavigationMetadata: Record<Exclude<keyof PersonRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PersonItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    request: {
        requestsMetadata: RequestRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
