/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CategoryRequestBuilderNavigationMetadata, type CategoryRequestBuilder } from './category/index.js';
// @ts-ignore
import { LocationRequestBuilderNavigationMetadata, type LocationRequestBuilder } from './location/index.js';
// @ts-ignore
import { PersonRequestBuilderNavigationMetadata, type PersonRequestBuilder } from './person/index.js';
// @ts-ignore
import { PhotoRequestBuilderNavigationMetadata, type PhotoRequestBuilder } from './photo/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The Category property
     */
    get category(): CategoryRequestBuilder;
    /**
     * The Location property
     */
    get location(): LocationRequestBuilder;
    /**
     * The Person property
     */
    get person(): PersonRequestBuilder;
    /**
     * The Photo property
     */
    get photo(): PhotoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    category: {
        navigationMetadata: CategoryRequestBuilderNavigationMetadata,
    },
    location: {
        navigationMetadata: LocationRequestBuilderNavigationMetadata,
    },
    person: {
        navigationMetadata: PersonRequestBuilderNavigationMetadata,
    },
    photo: {
        navigationMetadata: PhotoRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
