/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CategoryItemRequestBuilderRequestsMetadata, type CategoryItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { RequestRequestBuilderRequestsMetadata, type RequestRequestBuilder } from './request/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Category
 */
export interface CategoryRequestBuilder extends BaseRequestBuilder<CategoryRequestBuilder> {
    /**
     * The request property
     */
    get request(): RequestRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.Category.item collection
     * @param id Unique identifier of the item
     * @returns {CategoryItemRequestBuilder}
     */
     byId(id: Guid) : CategoryItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CategoryRequestBuilderUriTemplate = "{+baseurl}/api/Category";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CategoryRequestBuilderNavigationMetadata: Record<Exclude<keyof CategoryRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: CategoryItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    request: {
        requestsMetadata: RequestRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
