/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PhotoItemRequestBuilderNavigationMetadata, PhotoItemRequestBuilderRequestsMetadata, type PhotoItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { RequestRequestBuilderRequestsMetadata, type RequestRequestBuilder } from './request/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Photo
 */
export interface PhotoRequestBuilder extends BaseRequestBuilder<PhotoRequestBuilder> {
    /**
     * The request property
     */
    get request(): RequestRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.Photo.item collection
     * @param id Unique identifier of the item
     * @returns {PhotoItemRequestBuilder}
     */
     byId(id: Guid) : PhotoItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PhotoRequestBuilderUriTemplate = "{+baseurl}/api/Photo";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PhotoRequestBuilderNavigationMetadata: Record<Exclude<keyof PhotoRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: PhotoItemRequestBuilderRequestsMetadata,
        navigationMetadata: PhotoItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    request: {
        requestsMetadata: RequestRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
