/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { LocationItemRequestBuilderRequestsMetadata, type LocationItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { RequestRequestBuilderRequestsMetadata, type RequestRequestBuilder } from './request/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Location
 */
export interface LocationRequestBuilder extends BaseRequestBuilder<LocationRequestBuilder> {
    /**
     * The request property
     */
    get request(): RequestRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.Location.item collection
     * @param id Unique identifier of the item
     * @returns {LocationItemRequestBuilder}
     */
     byId(id: Guid) : LocationItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LocationRequestBuilderUriTemplate = "{+baseurl}/api/Location";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LocationRequestBuilderNavigationMetadata: Record<Exclude<keyof LocationRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: LocationItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    request: {
        requestsMetadata: RequestRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
