/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Guid, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface CategoryRequest extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The searchText property
     */
    searchText?: string | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface CategorySummary extends AdditionalDataHolder, Parsable {
    /**
     * The categoryName property
     */
    categoryName?: string | null;
    /**
     * The color property
     */
    color?: string | null;
    /**
     * The icon property
     */
    icon?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface CategoryViewModel extends AdditionalDataHolder, Parsable {
    /**
     * The categoryName property
     */
    categoryName?: string | null;
    /**
     * The color property
     */
    color?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The disabled property
     */
    disabled?: boolean | null;
    /**
     * The icon property
     */
    icon?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CategoryRequest}
 */
// @ts-ignore
export function createCategoryRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCategoryRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CategorySummary}
 */
// @ts-ignore
export function createCategorySummaryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCategorySummary;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CategoryViewModel}
 */
// @ts-ignore
export function createCategoryViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCategoryViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LocationRequest}
 */
// @ts-ignore
export function createLocationRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLocationRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LocationSummary}
 */
// @ts-ignore
export function createLocationSummaryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLocationSummary;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LocationViewModel}
 */
// @ts-ignore
export function createLocationViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLocationViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PersonRequest}
 */
// @ts-ignore
export function createPersonRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPersonRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PersonSummary}
 */
// @ts-ignore
export function createPersonSummaryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPersonSummary;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PersonViewModel}
 */
// @ts-ignore
export function createPersonViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPersonViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PhotoRequest}
 */
// @ts-ignore
export function createPhotoRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPhotoRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PhotoSummary}
 */
// @ts-ignore
export function createPhotoSummaryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPhotoSummary;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LocationSummary | PhotoViewModel_locationMember1}
 */
// @ts-ignore
export function createPhotoViewModel_locationFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPhotoViewModel_location;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PhotoViewModel_locationMember1}
 */
// @ts-ignore
export function createPhotoViewModel_locationMember1FromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPhotoViewModel_locationMember1;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PhotoViewModel}
 */
// @ts-ignore
export function createPhotoViewModelFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPhotoViewModel;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ProblemDetails}
 */
// @ts-ignore
export function createProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoProblemDetails;
}
/**
 * The deserialization information for the current model
 * @param CategoryRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCategoryRequest(categoryRequest: Partial<CategoryRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { categoryRequest.id = n.getGuidValue(); },
        "searchText": n => { categoryRequest.searchText = n.getStringValue(); },
        "tenantId": n => { categoryRequest.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CategorySummary The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCategorySummary(categorySummary: Partial<CategorySummary> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryName": n => { categorySummary.categoryName = n.getStringValue(); },
        "color": n => { categorySummary.color = n.getStringValue(); },
        "icon": n => { categorySummary.icon = n.getStringValue(); },
        "id": n => { categorySummary.id = n.getGuidValue(); },
        "tenantId": n => { categorySummary.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CategoryViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCategoryViewModel(categoryViewModel: Partial<CategoryViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryName": n => { categoryViewModel.categoryName = n.getStringValue(); },
        "color": n => { categoryViewModel.color = n.getStringValue(); },
        "description": n => { categoryViewModel.description = n.getStringValue(); },
        "disabled": n => { categoryViewModel.disabled = n.getBooleanValue(); },
        "icon": n => { categoryViewModel.icon = n.getStringValue(); },
        "id": n => { categoryViewModel.id = n.getGuidValue(); },
        "tenantId": n => { categoryViewModel.tenantId = n.getGuidValue(); },
        "updatedAt": n => { categoryViewModel.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LocationRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLocationRequest(locationRequest: Partial<LocationRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { locationRequest.id = n.getGuidValue(); },
        "searchText": n => { locationRequest.searchText = n.getStringValue(); },
        "tenantId": n => { locationRequest.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LocationSummary The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLocationSummary(locationSummary: Partial<LocationSummary> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { locationSummary.id = n.getGuidValue(); },
        "latitude": n => { locationSummary.latitude = n.getNumberValue(); },
        "locationName": n => { locationSummary.locationName = n.getStringValue(); },
        "longitude": n => { locationSummary.longitude = n.getNumberValue(); },
        "tenantId": n => { locationSummary.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LocationViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLocationViewModel(locationViewModel: Partial<LocationViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { locationViewModel.description = n.getStringValue(); },
        "disabled": n => { locationViewModel.disabled = n.getBooleanValue(); },
        "id": n => { locationViewModel.id = n.getGuidValue(); },
        "latitude": n => { locationViewModel.latitude = n.getNumberValue(); },
        "locationName": n => { locationViewModel.locationName = n.getStringValue(); },
        "longitude": n => { locationViewModel.longitude = n.getNumberValue(); },
        "reusable": n => { locationViewModel.reusable = n.getBooleanValue(); },
        "tenantId": n => { locationViewModel.tenantId = n.getGuidValue(); },
        "updatedAt": n => { locationViewModel.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PersonRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPersonRequest(personRequest: Partial<PersonRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { personRequest.id = n.getGuidValue(); },
        "searchText": n => { personRequest.searchText = n.getStringValue(); },
        "tenantId": n => { personRequest.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PersonSummary The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPersonSummary(personSummary: Partial<PersonSummary> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { personSummary.id = n.getGuidValue(); },
        "personName": n => { personSummary.personName = n.getStringValue(); },
        "tenantId": n => { personSummary.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PersonViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPersonViewModel(personViewModel: Partial<PersonViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { personViewModel.description = n.getStringValue(); },
        "disabled": n => { personViewModel.disabled = n.getBooleanValue(); },
        "id": n => { personViewModel.id = n.getGuidValue(); },
        "personName": n => { personViewModel.personName = n.getStringValue(); },
        "tenantId": n => { personViewModel.tenantId = n.getGuidValue(); },
        "updatedAt": n => { personViewModel.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PhotoRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPhotoRequest(photoRequest: Partial<PhotoRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categoryId": n => { photoRequest.categoryId = n.getGuidValue(); },
        "id": n => { photoRequest.id = n.getGuidValue(); },
        "locationId": n => { photoRequest.locationId = n.getGuidValue(); },
        "personId": n => { photoRequest.personId = n.getGuidValue(); },
        "searchText": n => { photoRequest.searchText = n.getStringValue(); },
        "takenFromDate": n => { photoRequest.takenFromDate = n.getDateValue(); },
        "takenToData": n => { photoRequest.takenToData = n.getDateValue(); },
        "tenantId": n => { photoRequest.tenantId = n.getGuidValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PhotoSummary The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPhotoSummary(photoSummary: Partial<PhotoSummary> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "filename": n => { photoSummary.filename = n.getStringValue(); },
        "id": n => { photoSummary.id = n.getGuidValue(); },
        "locationId": n => { photoSummary.locationId = n.getGuidValue(); },
        "takenOn": n => { photoSummary.takenOn = n.getDateValue(); },
        "tenantId": n => { photoSummary.tenantId = n.getGuidValue(); },
        "title": n => { photoSummary.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PhotoViewModel The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPhotoViewModel(photoViewModel: Partial<PhotoViewModel> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "categories": n => { photoViewModel.categories = n.getCollectionOfObjectValues<CategorySummary>(createCategorySummaryFromDiscriminatorValue); },
        "description": n => { photoViewModel.description = n.getStringValue(); },
        "disabled": n => { photoViewModel.disabled = n.getBooleanValue(); },
        "filename": n => { photoViewModel.filename = n.getStringValue(); },
        "id": n => { photoViewModel.id = n.getGuidValue(); },
        "location": n => { photoViewModel.location = n.getObjectValue<LocationSummary>(createLocationSummaryFromDiscriminatorValue) ?? n.getObjectValue<PhotoViewModel_locationMember1>(createPhotoViewModel_locationMember1FromDiscriminatorValue); },
        "locationId": n => { photoViewModel.locationId = n.getGuidValue(); },
        "persons": n => { photoViewModel.persons = n.getCollectionOfObjectValues<PersonSummary>(createPersonSummaryFromDiscriminatorValue); },
        "takenOn": n => { photoViewModel.takenOn = n.getDateValue(); },
        "tenantId": n => { photoViewModel.tenantId = n.getGuidValue(); },
        "title": n => { photoViewModel.title = n.getStringValue(); },
        "updatedAt": n => { photoViewModel.updatedAt = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PhotoViewModel_location The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPhotoViewModel_location(photoViewModel_location: Partial<LocationSummary | PhotoViewModel_locationMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoLocationSummary(photoViewModel_location as LocationSummary),
        ...deserializeIntoPhotoViewModel_locationMember1(photoViewModel_location as PhotoViewModel_locationMember1),
    }
}
/**
 * The deserialization information for the current model
 * @param PhotoViewModel_locationMember1 The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPhotoViewModel_locationMember1(photoViewModel_locationMember1: Partial<PhotoViewModel_locationMember1> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @param ProblemDetails The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoProblemDetails(problemDetails: Partial<ProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { problemDetails.detail = n.getStringValue(); },
        "instance": n => { problemDetails.instance = n.getStringValue(); },
        "status": n => { problemDetails.status = n.getNumberValue(); },
        "title": n => { problemDetails.title = n.getStringValue(); },
        "type": n => { problemDetails.type = n.getStringValue(); },
    }
}
export interface LocationRequest extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The searchText property
     */
    searchText?: string | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface LocationSummary extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The latitude property
     */
    latitude?: number | null;
    /**
     * The locationName property
     */
    locationName?: string | null;
    /**
     * The longitude property
     */
    longitude?: number | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface LocationViewModel extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The disabled property
     */
    disabled?: boolean | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The latitude property
     */
    latitude?: number | null;
    /**
     * The locationName property
     */
    locationName?: string | null;
    /**
     * The longitude property
     */
    longitude?: number | null;
    /**
     * The reusable property
     */
    reusable?: boolean | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface PersonRequest extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The searchText property
     */
    searchText?: string | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface PersonSummary extends AdditionalDataHolder, Parsable {
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The personName property
     */
    personName?: string | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface PersonViewModel extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The disabled property
     */
    disabled?: boolean | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The personName property
     */
    personName?: string | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export interface PhotoRequest extends AdditionalDataHolder, Parsable {
    /**
     * The categoryId property
     */
    categoryId?: Guid | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The locationId property
     */
    locationId?: Guid | null;
    /**
     * The personId property
     */
    personId?: Guid | null;
    /**
     * The searchText property
     */
    searchText?: string | null;
    /**
     * The takenFromDate property
     */
    takenFromDate?: Date | null;
    /**
     * The takenToData property
     */
    takenToData?: Date | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
}
export interface PhotoSummary extends AdditionalDataHolder, Parsable {
    /**
     * The filename property
     */
    filename?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The locationId property
     */
    locationId?: Guid | null;
    /**
     * The takenOn property
     */
    takenOn?: Date | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface PhotoViewModel extends AdditionalDataHolder, Parsable {
    /**
     * The categories property
     */
    categories?: CategorySummary[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The disabled property
     */
    disabled?: boolean | null;
    /**
     * The filename property
     */
    filename?: string | null;
    /**
     * The id property
     */
    id?: Guid | null;
    /**
     * The location property
     */
    location?: LocationSummary | PhotoViewModel_locationMember1 | null;
    /**
     * The locationId property
     */
    locationId?: Guid | null;
    /**
     * The persons property
     */
    persons?: PersonSummary[] | null;
    /**
     * The takenOn property
     */
    takenOn?: Date | null;
    /**
     * The tenantId property
     */
    tenantId?: Guid | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The updatedAt property
     */
    updatedAt?: Date | null;
}
export type PhotoViewModel_location = LocationSummary | PhotoViewModel_locationMember1;
export interface PhotoViewModel_locationMember1 extends AdditionalDataHolder, Parsable {
}
export interface ProblemDetails extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * The detail property
     */
    detail?: string | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * Serializes information the current object
 * @param CategoryRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCategoryRequest(writer: SerializationWriter, categoryRequest: Partial<CategoryRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!categoryRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", categoryRequest.id);
    writer.writeStringValue("searchText", categoryRequest.searchText);
    writer.writeGuidValue("tenantId", categoryRequest.tenantId);
    writer.writeAdditionalData(categoryRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CategorySummary The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCategorySummary(writer: SerializationWriter, categorySummary: Partial<CategorySummary> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!categorySummary || isSerializingDerivedType) { return; }
    writer.writeStringValue("categoryName", categorySummary.categoryName);
    writer.writeStringValue("color", categorySummary.color);
    writer.writeStringValue("icon", categorySummary.icon);
    writer.writeGuidValue("id", categorySummary.id);
    writer.writeGuidValue("tenantId", categorySummary.tenantId);
    writer.writeAdditionalData(categorySummary.additionalData);
}
/**
 * Serializes information the current object
 * @param CategoryViewModel The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCategoryViewModel(writer: SerializationWriter, categoryViewModel: Partial<CategoryViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!categoryViewModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("categoryName", categoryViewModel.categoryName);
    writer.writeStringValue("color", categoryViewModel.color);
    writer.writeStringValue("description", categoryViewModel.description);
    writer.writeBooleanValue("disabled", categoryViewModel.disabled);
    writer.writeStringValue("icon", categoryViewModel.icon);
    writer.writeGuidValue("id", categoryViewModel.id);
    writer.writeGuidValue("tenantId", categoryViewModel.tenantId);
    writer.writeDateValue("updatedAt", categoryViewModel.updatedAt);
    writer.writeAdditionalData(categoryViewModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LocationRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLocationRequest(writer: SerializationWriter, locationRequest: Partial<LocationRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!locationRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", locationRequest.id);
    writer.writeStringValue("searchText", locationRequest.searchText);
    writer.writeGuidValue("tenantId", locationRequest.tenantId);
    writer.writeAdditionalData(locationRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LocationSummary The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLocationSummary(writer: SerializationWriter, locationSummary: Partial<LocationSummary> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!locationSummary || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", locationSummary.id);
    writer.writeNumberValue("latitude", locationSummary.latitude);
    writer.writeStringValue("locationName", locationSummary.locationName);
    writer.writeNumberValue("longitude", locationSummary.longitude);
    writer.writeGuidValue("tenantId", locationSummary.tenantId);
    writer.writeAdditionalData(locationSummary.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LocationViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLocationViewModel(writer: SerializationWriter, locationViewModel: Partial<LocationViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!locationViewModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", locationViewModel.description);
    writer.writeBooleanValue("disabled", locationViewModel.disabled);
    writer.writeGuidValue("id", locationViewModel.id);
    writer.writeNumberValue("latitude", locationViewModel.latitude);
    writer.writeStringValue("locationName", locationViewModel.locationName);
    writer.writeNumberValue("longitude", locationViewModel.longitude);
    writer.writeBooleanValue("reusable", locationViewModel.reusable);
    writer.writeGuidValue("tenantId", locationViewModel.tenantId);
    writer.writeDateValue("updatedAt", locationViewModel.updatedAt);
    writer.writeAdditionalData(locationViewModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PersonRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePersonRequest(writer: SerializationWriter, personRequest: Partial<PersonRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!personRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", personRequest.id);
    writer.writeStringValue("searchText", personRequest.searchText);
    writer.writeGuidValue("tenantId", personRequest.tenantId);
    writer.writeAdditionalData(personRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PersonSummary The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePersonSummary(writer: SerializationWriter, personSummary: Partial<PersonSummary> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!personSummary || isSerializingDerivedType) { return; }
    writer.writeGuidValue("id", personSummary.id);
    writer.writeStringValue("personName", personSummary.personName);
    writer.writeGuidValue("tenantId", personSummary.tenantId);
    writer.writeAdditionalData(personSummary.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PersonViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePersonViewModel(writer: SerializationWriter, personViewModel: Partial<PersonViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!personViewModel || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", personViewModel.description);
    writer.writeBooleanValue("disabled", personViewModel.disabled);
    writer.writeGuidValue("id", personViewModel.id);
    writer.writeStringValue("personName", personViewModel.personName);
    writer.writeGuidValue("tenantId", personViewModel.tenantId);
    writer.writeDateValue("updatedAt", personViewModel.updatedAt);
    writer.writeAdditionalData(personViewModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PhotoRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePhotoRequest(writer: SerializationWriter, photoRequest: Partial<PhotoRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!photoRequest || isSerializingDerivedType) { return; }
    writer.writeGuidValue("categoryId", photoRequest.categoryId);
    writer.writeGuidValue("id", photoRequest.id);
    writer.writeGuidValue("locationId", photoRequest.locationId);
    writer.writeGuidValue("personId", photoRequest.personId);
    writer.writeStringValue("searchText", photoRequest.searchText);
    writer.writeDateValue("takenFromDate", photoRequest.takenFromDate);
    writer.writeDateValue("takenToData", photoRequest.takenToData);
    writer.writeGuidValue("tenantId", photoRequest.tenantId);
    writer.writeAdditionalData(photoRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PhotoSummary The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePhotoSummary(writer: SerializationWriter, photoSummary: Partial<PhotoSummary> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!photoSummary || isSerializingDerivedType) { return; }
    writer.writeStringValue("filename", photoSummary.filename);
    writer.writeGuidValue("id", photoSummary.id);
    writer.writeGuidValue("locationId", photoSummary.locationId);
    writer.writeDateValue("takenOn", photoSummary.takenOn);
    writer.writeGuidValue("tenantId", photoSummary.tenantId);
    writer.writeStringValue("title", photoSummary.title);
    writer.writeAdditionalData(photoSummary.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PhotoViewModel The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePhotoViewModel(writer: SerializationWriter, photoViewModel: Partial<PhotoViewModel> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!photoViewModel || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<CategorySummary>("categories", photoViewModel.categories, serializeCategorySummary);
    writer.writeStringValue("description", photoViewModel.description);
    writer.writeBooleanValue("disabled", photoViewModel.disabled);
    writer.writeStringValue("filename", photoViewModel.filename);
    writer.writeGuidValue("id", photoViewModel.id);
    writer.writeObjectValue<LocationSummary | PhotoViewModel_locationMember1>("location", photoViewModel.location, serializePhotoViewModel_location);
    writer.writeGuidValue("locationId", photoViewModel.locationId);
    writer.writeCollectionOfObjectValues<PersonSummary>("persons", photoViewModel.persons, serializePersonSummary);
    writer.writeDateValue("takenOn", photoViewModel.takenOn);
    writer.writeGuidValue("tenantId", photoViewModel.tenantId);
    writer.writeStringValue("title", photoViewModel.title);
    writer.writeDateValue("updatedAt", photoViewModel.updatedAt);
    writer.writeAdditionalData(photoViewModel.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PhotoViewModel_location The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePhotoViewModel_location(writer: SerializationWriter, photoViewModel_location: Partial<LocationSummary | PhotoViewModel_locationMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    serializeLocationSummary(writer, photoViewModel_location as LocationSummary);
    serializePhotoViewModel_locationMember1(writer, photoViewModel_location as PhotoViewModel_locationMember1);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PhotoViewModel_locationMember1 The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePhotoViewModel_locationMember1(writer: SerializationWriter, photoViewModel_locationMember1: Partial<PhotoViewModel_locationMember1> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!photoViewModel_locationMember1 || isSerializingDerivedType) { return; }
    writer.writeAdditionalData(photoViewModel_locationMember1.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param ProblemDetails The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeProblemDetails(writer: SerializationWriter, problemDetails: Partial<ProblemDetails> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!problemDetails || isSerializingDerivedType) { return; }
    writer.writeStringValue("detail", problemDetails.detail);
    writer.writeStringValue("instance", problemDetails.instance);
    writer.writeNumberValue("status", problemDetails.status);
    writer.writeStringValue("title", problemDetails.title);
    writer.writeStringValue("type", problemDetails.type);
    writer.writeAdditionalData(problemDetails.additionalData);
}
/* tslint:enable */
/* eslint-enable */
