/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createPersonSummaryFromDiscriminatorValue, serializePersonRequest, serializePersonSummary, type PersonRequest, type PersonSummary } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/Person/request
 */
export interface RequestRequestBuilder extends BaseRequestBuilder<RequestRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<PersonSummary[]>}
     */
     post(body: PersonRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<PersonSummary[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: PersonRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RequestRequestBuilderUriTemplate = "{+baseurl}/api/Person/request";
/**
 * Metadata for all the requests in the request builder.
 */
export const RequestRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: RequestRequestBuilderUriTemplate,
        responseBodyContentType: "text/plain;q=0.9",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createPersonSummaryFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializePersonRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
